import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { GeneratedFileCollisionError } from '../core/errors.js';
import { GENERATED_MARKER } from './renderer.js';

export interface CheckResult {
  ok: boolean;
  missing: string[];
  stale: string[];
}

export function isGenerated(content: string): boolean {
  return content.includes(GENERATED_MARKER);
}

export function checkSkillFiles(skillPath: string, expectedContent: string): CheckResult {
  if (!existsSync(skillPath)) {
    return { ok: false, missing: [skillPath], stale: [] };
  }
  const actual = readFileSync(skillPath, 'utf8');
  if (actual !== expectedContent) {
    return { ok: false, missing: [], stale: [skillPath] };
  }
  return { ok: true, missing: [], stale: [] };
}

export function writeGenerated(targetPath: string, content: string, force: boolean): void {
  if (existsSync(targetPath)) {
    const existing = readFileSync(targetPath, 'utf8');
    if (!isGenerated(existing) && !force) {
      throw new GeneratedFileCollisionError(
        `file exists and was not generated by singularity-cli: ${targetPath}`,
        { path: targetPath },
      );
    }
  }
  mkdirSync(path.dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, content, 'utf8');
}
