export {
  createSingularityAdapter,
  type SingularityAdapter,
  type SingularityAdapterConfig,
  type CreateTaskRequest,
  type UpdateTaskRequest,
  type CompleteTaskRequest,
  type MoveTaskRequest,
  type CreateProjectRequest,
  type UpdateProjectRequest,
  type CreateNoteRequest,
  type UpdateNoteRequest,
  type CreateHabitRequest,
  type UpdateHabitRequest,
  type CompleteHabitRequest,
  type CreateTagRequest,
  type UpdateTagRequest,
  type CreateTaskGroupRequest,
  type UpdateTaskGroupRequest,
} from './adapter.js';
